# Generated by Django 3.0.7 on 2020-06-12 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
        migrations.RemoveField(
            model_name='cards',
            name='cardname',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='cardnos',
        ),
        migrations.AddField(
            model_name='cards',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='is_reported',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
