# Generated by Django 3.0.7 on 2020-06-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200612_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
